# This is a basic workflow to help you get started with Actions

name: Test Workflow

on:
  pull_request:
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        GOMODCACHE: home/.cache/go-mod
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Cache local Go cache
        id: cache-go-mods
        uses: actions/cache@v2
        with:
          path: home/.cache/go-mod
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-gomod-
            ${{ runner.os }}-

      - name: Execute go module download test
        run: |
          mkdir -p ~/.cache
          ./run_test.sh
        timeout-minutes: 60
